"""body change type(string to text)

Revision ID: 261a6b0a2bc9
Revises: 4bb0af9b183a
Create Date: 2023-07-13 09:30:18.280719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261a6b0a2bc9'
down_revision = '4bb0af9b183a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
