"""body change type(string to text1)

Revision ID: 4154845b3624
Revises: 261a6b0a2bc9
Create Date: 2023-07-13 09:48:40.558386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4154845b3624'
down_revision = '261a6b0a2bc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
