"""default

Revision ID: 4bb0af9b183a
Revises: 245b525bd61d
Create Date: 2023-06-22 15:37:17.440462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb0af9b183a'
down_revision = '245b525bd61d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
