"""body change type(string to text2)

Revision ID: 6542aa0700f3
Revises: 4154845b3624
Create Date: 2023-07-13 09:51:20.203924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6542aa0700f3'
down_revision = '4154845b3624'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
